# Generated by Django 5.0.2 on 2024-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_transaction_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction Datetime'),
        ),
    ]
